var ui={
	line:[
		{
			confele:"color",
			dom:"input",
			type:"color"
		},
		{
			confele:"width",
			dom:"input",
			type:"range",
			range:{
				min:1,
				max:48,
				step:1
			}
		},
		{
			confele:"opacity",
			dom:"input",
			type:"range",
			range:{
				min:1,
				max:100,
				step:1
			}
		}
	],
	direct:[
		{
			confele:"color",
			dom:"input",
			type:"color"
		},
		{
			confele:"width",
			dom:"input",
			type:"range",
			range:{
				min:12,
				max:48,
				step:1
			}
		},
		{
			confele:"opacity",
			dom:"input",
			type:"range",
			range:{
				min:1,
				max:100,
				step:1
			}
		},
		{
			confele:"style",
			dom:"select",
			select:["follow","center","top","ui_bottom","left","right","leftbottom","lefttop","righttop","hover"]
		}
	],
	tip:[
		{
			confele:"color",
			dom:"input",
			type:"color"
		},
		{
			confele:"bgcolor",
			dom:"input",
			type:"color"
		},
		{
			confele:"width",
			dom:"input",
			type:"range",
			range:{
				min:12,
				max:48,
				step:1
			}
		},
		{
			confele:"opacity",
			dom:"input",
			type:"range",
			range:{
				min:1,
				max:100,
				step:1
			}
		},
		{
			confele:"style",
			dom:"select",
			select:["follow","center","top","ui_bottom","left","right","leftbottom","lefttop","righttop","hover"]

		},
		{
			confele:"withdir",
			dom:"input",
			type:"checkbox"
		}
	],
	note:[
		{
			confele:"color",
			dom:"input",
			type:"color"
		},
		{
			confele:"width",
			dom:"input",
			type:"range",
			range:{
				min:12,
				max:48,
				step:1
			}
		},
		{
			confele:"opacity",
			dom:"input",
			type:"range",
			range:{
				min:1,
				max:100,
				step:1
			}
		},
		{
			confele:"style",
			dom:"select",
			select:["follow","center","top","ui_bottom","left","right","leftbottom","lefttop","righttop","hover"]
		}
	],
	allaction:[
		{
			confele:"color",
			dom:"input",
			type:"color"
		},
		{
			confele:"bgcolor",
			dom:"input",
			type:"color"
		},
		{
			confele:"width",
			dom:"input",
			type:"range",
			range:{
				min:12,
				max:48,
				step:1
			}
		},
		{
			confele:"opacity",
			dom:"input",
			type:"range",
			range:{
				min:1,
				max:100,
				step:1
			}
		},
		{
			confele:"style",
			dom:"select",
			select:["follow","center","top","ui_bottom","left","right","leftbottom","lefttop","righttop","hover"]
		}
	]
}
var menuModel={
	fn:["general","mges","drg"],
	main:["fnswitch","general","mges","sdrg","drg"],
	fnswitch:["setting"],
	general:["setting","searchmgr"],
	mges:["setting","ui","gesmgr"],
	sdrg:["setting","tsdrg","lsdrg","isdrg"],
	drg:["setting","ui","tdrg","ldrg","idrg"],
	sfn:["settings"],
	apps:["settings"]
}